// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztlothznntjfvrmncyam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bG90aHpubnRqZnZybW5jeWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjMyNzcsImV4cCI6MjA1ODgzOTI3N30.dPYiOTa5LnGFEYZh2p1lSR_XYa61TYOPbAzjJzSq5EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);